mod app;
mod character_commands;
mod character_files;
mod characters;
mod desktop;
mod device_wake;
mod domain;
mod inference;
mod models;
mod playback;
mod resources;
mod store;
mod story;
mod story_editor;
mod story_host;
pub mod talk;
mod talk_editor_commands;
mod talk_host;
mod types;
mod widget_commands;
mod widget_connections;
mod widgets;
mod wordbook;

pub use app::lifecycle::run;
