mod app;
mod behavior;
mod character_collision;
mod character_collision_host;
mod character_commands;
mod character_files;
mod character_sprites;
mod characters;
mod desktop;
mod desktop_geometry;
mod desktop_menu;
mod desktop_toys;
mod device_wake;
mod domain;
mod inference;
mod legacy_names;
mod memo_notes;
mod memory_commands;
mod models;
mod nlp;
mod music_bridge;
mod planner_notifications;
mod planner_windows;
mod playback;
mod resources;
mod store;
mod story;
mod story_host;
pub mod talk;
mod talk_commands;
mod talk_host;
mod types;
mod updater;
mod widget_backgrounds;
mod widget_commands;
mod widget_connections;
mod widgets;
mod wordbook;

pub use app::lifecycle::run;

pub(crate) use app::lifecycle::{prepare_update_install, restore_update_install};
#[cfg(test)]
pub(crate) use app::tests as lifecycle_tests;
pub(crate) use app::windows::{hide_boxes, open_settings, quit_app, set_paused, show_boxes};
pub(crate) use app::{interrupt, lock, now, publish, snapshot, unavailable, AppState};
pub(crate) use character_commands::open_characters;
pub(crate) use widget_commands::{open_widget, open_widgets};
